resources:
  repositories:
    - repository: ExampleDocs
      type: github
      endpoint: PalConnection
      name: webdoc-js/example-documentation

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
- checkout: ExampleDocs
  persistCredentials: true

- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'Install Node.js'

- script: |
    ls -a | grep -Fv -e README.md -e .git -e . -e .. | xargs -r rm -r
  displayName: "Clear example-documentation"
  workingDirectory: example-documentation

- script: |
    ls -a
    npm install
    node node_modules/.bin/lerna bootstrap
  displayName: "Install webdoc"
  workingDirectory: webdoc

- script: |
    rm -rf ./docs
    cd .. && npm run build && cd example
    npm run generate
    cp -r ./docs/* ../../example-documentation/
  displayName: "Generate example documentation & copy to webdoc-js/example-documentation"
  workingDirectory: webdoc/example

- script: |
    git config --global user.email "sukantk2002@outlook.com"
    git config --global user.name "Shukant Pal"
    git checkout master
    git add .
    git commit . -m "Automatic documentation update"
    git push --force origin master
  displayName: "Checkout example-documentation and push generated documentation"
  workingDirectory: example-documentation
