resources:
  repositories:
    - repository: ExampleDocs
      type: github
      endpoint: PalConnection
      name: webdoc-js/example-documentation

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
- checkout: ExampleDocs
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm install -g 
    npm run build
  displayName: "Install and build project"
  workingDirectory: webdoc

- script: |
    npx flow
  displayName: "Type check"
  workingDirectory: webdoc
  continueOnError: true

- script: |
    npx eslint ./packages/*/src/**/*.js
  displayName: "Lint"
  workingDirectory: webdoc
  continueOnError: true

- script: |
    npm run unit-test
  displayName: "Run unit tests"
  workingDirectory: webdoc